name: router_example
description: An example project for the flutter router.

dependencies:
  flutter:
    sdk: flutter
  fluro:
    path: ../
flutter:
  uses-material-design: false
  assets:
    - assets/images/logo_fluro.png
    - assets/images/acc_boom.png
    - assets/images/ic_result_hz.png
    - assets/images/ic_function_hz.png
    - assets/images/ic_transform_custom_hz.png
    - assets/images/ic_transform_fade_in_hz.png
    - assets/images/ic_transform_fade_out_hz.png
    - assets/images/ic_transform_global_hz.png
    - assets/images/ic_transform_native_hz.png
  fonts:
    - family: Lazer84
      fonts:
        - asset: assets/fonts/Lazer84.ttf