language: dart
dart:
  - dev
os:
  - linux
sudo: false

env:
  - FLUTTER_VERSION=dev

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++6
      - fonts-droid

matrix:
  allow_failures:
    - env: FLUTTER_VERSION=dev

before_script:
  - pwd
  - git clone https://github.com/flutter/flutter.git -b $FLUTTER_VERSION
  - export PATH=`pwd`/flutter/bin:`pwd`/flutter/bin/cache/dart-sdk/bin:$PATH
  - flutter doctor
script:
  - pwd
  - ./flutter/bin/flutter test --coverage
after_success:
  - bash <(curl -s https://codecov.io/bash) -t $CODE_COV_TOKEN

cache:
  directories:
    - $HOME/.pub-cache