name: fluro
description: >
  The brightest, hippest, coolest router for Flutter. Fluro is a companion to the Flutter routing mechanism
  which adds flexible routing options like wildcards, named parameters and clearer route definitions.
version: 1.3.2
author: Yakka, LLC <code@theyakka.com>
homepage: https://github.com/theyakka/fluro

environment:
  sdk: ">=2.0.0-dev.61.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^0.12.37

flutter:
  uses-material-design: false
