name: fluro_fork
description: >
  This is a fork of Fluro. Fluro is a Flutter routing library that adds flexible routing options like wildcards, named
  parameters and clear route definitions. 
version: 0.0.1
homepage: https://github.com/brianschardt/fluro

environment:
  sdk: ">=2.6.0 <3.0.0"
  flutter: ">=1.12.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.6.0

flutter:
  uses-material-design: false
